name: chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  path: ^1.8.3
  permission_handler: ^11.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/content/

